import { Metadata } from "next";
import HeroSection from "@/components/HeroSection";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "სასარგებლო ინფორმაცია",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <div className="mb-8 sm:mb-12">
        <HeroSection imageUrl="/info/back.webp" overlay="bg-black/30" />
      </div>
      <div className="flex flex-col lg:flex-row container mx-auto px-2 sm:px-4 md:px-4 lg:px-10">
        <Sidebar />
        <main className="flex-1 pt-5 lg:pl-1 px-4">{children}</main>
      </div>
    </main>
  );
}
