import { Metadata } from "next";
import { HeroSection } from "@/components/hero-section";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "სასარგებლო ინფორმაცია",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <div className="mb-8 sm:mb-12">
        <HeroSection
          image="/info/back.webp"
          title="სახარვგებული ინფორმაცია"
          description="სანამ საქართველოში ჩამოხვალ, მნიშვნელოვანია გაეცნო ჩვენი ქვეყნის ცხოვრების სტილსა და ისეთ საჭირო დეტალებს, როგორებიცაა, სავიზო პოლიტიკა, ადგილობრივი და რეგიონული ტრანსპორტი, ამინდი, კლიმატი, სასტუმროთა ქსელები და სხვა."
          overlay="bg-black/30"
        />
      </div>
      <div className="flex flex-col lg:flex-row max-w-7xl mx-auto px-4 sm:px-6 lg:px-10">
        <Sidebar />
        <main className="flex-1 pt-5 lg:pl-1 px-4">{children}</main>
      </div>
    </main>
  );
}
